### ISSUE TITLE
installing in kerberos cluster it show error 

### ISSUE THREAD

**Issue by kiranbhakre** [steven-dfheinz/dfhz_hue_mpack#3]
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/common-services/HUE/4.6.0/package/scripts/hue_server.py", line 76, in <module>
    HueServer().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/common-services/HUE/4.6.0/package/scripts/hue_server.py", line 14, in install
    import params
  File "/var/lib/ambari-agent/cache/common-services/HUE/4.6.0/package/scripts/params.py", line 157, in <module>
    hue_principal = config['configurations']['hue-desktop-site']['kerberos_hue_principal'].replace('_HOST',http_host)
TypeError: coercing to Unicode: need string or buffer, instance found

**Comment by steven-matison** [comment]
Hello,  I did not work on this as far as kerberizing.   The approach would be to install w/o kerberos and then modify the he configuration according to hue documentation to kerberize.  Then complete the required steps to modify each plugin (hive,hdfs,etc) to satisfy the kerberos requirements for each.  This would be a very advanced task as such not an issue with the demo management pack.

**Comment by meenzoon** [comment]
@kiranbhakre 
I found a same problem chagned the '/var/lib/ambari-agent/cache/common-services/HUE/4.6.0/package/scripts/params.py' 92 line.
`http_host = config['hostname']   =>
   http_host = config['configurations']['hue-env']['http_host']`
Ambari: 2.7.5.0, hdp: 3.1.4.0-315
Thank you.
