### ISSUE TITLE
Failure to install with File exists error

### ISSUE THREAD

**Issue by ajs6f** [steven-dfheinz/dfhz_hue_mpack#5]
Thanks for all this work to create a Hue management pack! I'm trying to install it but getting a "File exists" error. This seems odd to me-- I'm not sure what the collision would be, but I cannot figure out what the colliding file is, either. (`--verbose` doesn't give any more information).

Does this ring any bells? Any advice or info much appreciated!

CentOS 7.7.1908, Ambari 2.7.5

```
[sorokaa@test07 ~]$ sudo ambari-server install-mpack --mpack=https://github.com/steven-matison/dfhz_hue_mpack/raw/master/hue_mpack-4.6.0-0.1.tar.gz --verbose
Using python  /usr/bin/python
Installing management pack
INFO: Loading properties from /etc/ambari-server/conf/ambari.properties
INFO: Installing management pack https://github.com/steven-matison/dfhz_hue_mpack/raw/master/hue_mpack-4.6.0-0.1.tar.gz
INFO: Loading properties from /etc/ambari-server/conf/ambari.properties
INFO: Download management pack to temp location /var/lib/ambari-server/data/tmp/hue_mpack-4.6.0-0.1.tar.gz
INFO: Trying to download https://github.com/steven-matison/dfhz_hue_mpack/raw/master/hue_mpack-4.6.0-0.1.tar.gz to /var/lib/ambari-server/data/tmp/hue_mpack-4.6.0-0.1.tar.gz with python lib [urllib2].
INFO: Downloading to: /var/lib/ambari-server/data/tmp/hue_mpack-4.6.0-0.1.tar.gz Bytes: 69284

INFO: Finished downloading https://github.com/steven-matison/dfhz_hue_mpack/raw/master/hue_mpack-4.6.0-0.1.tar.gz to /var/lib/ambari-server/data/tmp/hue_mpack-4.6.0-0.1.tar.gz
INFO: Loading properties from /etc/ambari-server/conf/ambari.properties
INFO: Expand management pack at temp location /var/lib/ambari-server/data/tmp/hue_mpack-4.6.0-0.1
2021-02-11 15:57:26,559 - Execute[('tar', '-xf', '/var/lib/ambari-server/data/tmp/hue_mpack-4.6.0-0.1.tar.gz', '-C', '/var/lib/ambari-server/data/tmp/')] {'tries': 3, 'sudo': True, 'try_sleep': 1}
INFO: Loading properties from /etc/ambari-server/conf/ambari.properties
INFO: Loading properties from /etc/ambari-server/conf/ambari.properties
INFO: Stage management pack hue-ambari.mpack-4.6.0 to staging location /var/lib/ambari-server/resources/mpacks/hue-ambari.mpack-4.6.0
INFO: Processing artifact HUE-common-services of type service-definitions in /var/lib/ambari-server/resources/mpacks/hue-ambari.mpack-4.6.0/common-services
INFO: Loading properties from /etc/ambari-server/conf/ambari.properties
INFO: Symlink: /var/lib/ambari-server/resources/common-services/HUE/4.6.0
INFO: Processing artifact HUE-addon-services of type stack-addon-service-definitions in /var/lib/ambari-server/resources/mpacks/hue-ambari.mpack-4.6.0/addon-services
INFO: Loading properties from /etc/ambari-server/conf/ambari.properties
Traceback (most recent call last):
  File "/usr/sbin/ambari-server.py", line 1078, in <module>
    mainBody()
  File "/usr/sbin/ambari-server.py", line 1048, in mainBody
    main(options, args, parser)
  File "/usr/sbin/ambari-server.py", line 998, in main
    action_obj.execute()
  File "/usr/sbin/ambari-server.py", line 78, in execute
    self.fn(*self.args, **self.kwargs)
  File "/usr/lib/ambari-server/lib/ambari_server/setupMpacks.py", line 902, in install_mpack
    (mpack_metadata, mpack_name, mpack_version, mpack_staging_dir, mpack_archive_path) = _install_mpack(options, replay_mode)
  File "/usr/lib/ambari-server/lib/ambari_server/setupMpacks.py", line 798, in _install_mpack
    process_stack_addon_service_definitions_artifact(artifact, artifact_source_dir, options)
  File "/usr/lib/ambari-server/lib/ambari_server/setupMpacks.py", line 557, in process_stack_addon_service_definitions_artifact
    sudo.symlink(source_service_version_path, dest_link)
  File "/usr/lib/ambari-server/lib/resource_management/core/sudo.py", line 130, in symlink
    os.symlink(source, link_name)
OSError: [Errno 17] File exists
```

**Comment by steven-matison** [comment]
The solution is to delete the symlink that already exists.  Not sure if you are doing multiple install attempts, but I have seen similar to above doing many install attempts in iterations.  Follow the error to line 130 and comment that line, or delete the symlink from previous attempt.
